/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.MovimentoDAO;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author asfmegas
 */
public class LimpezaBancoGUI extends javax.swing.JFrame {
    private int definiTabela;
    private ButtonGroup bg;
    /**
     * Creates new form LimpezaBancoGUI
     */
    public LimpezaBancoGUI() {
        setTitle("LIMPEZA DE BANCO DE DADOS - SADA V 1.1");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        jtInfo.setEditable(false);
        bg = new ButtonGroup();
        bg.add(jrAluno);
        bg.add(jrCurso);
        bg.add(jrDisciplina);
        bg.add(jrGeral);
        bg.add(jrMovimento);
        jrGeral.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jrGeral = new javax.swing.JRadioButton();
        jrMovimento = new javax.swing.JRadioButton();
        jrCurso = new javax.swing.JRadioButton();
        jrDisciplina = new javax.swing.JRadioButton();
        jrAluno = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInfo = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jbVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Limpeza de Banco"));

        jbLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbLimpar.setForeground(new java.awt.Color(0, 0, 153));
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/banco_limpar-sada.png"))); // NOI18N
        jbLimpar.setText("LIMPAR");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jrGeral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrGeral.setText("Apagar todos os dados do banco");
        jrGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrGeralActionPerformed(evt);
            }
        });

        jrMovimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrMovimento.setText("Apagar dados das movimentações");
        jrMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMovimentoActionPerformed(evt);
            }
        });

        jrCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrCurso.setText("Apagar dados dos cursos");
        jrCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCursoActionPerformed(evt);
            }
        });

        jrDisciplina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrDisciplina.setText("Apagar dados das disciplinas");
        jrDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDisciplinaActionPerformed(evt);
            }
        });

        jrAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAluno.setText("Apagar dados dos alunos");
        jrAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrAluno)
                    .addComponent(jrMovimento)
                    .addComponent(jrGeral)
                    .addComponent(jrDisciplina)
                    .addComponent(jrCurso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrMovimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtInfo.setBackground(new java.awt.Color(51, 204, 255));
        jtInfo.setColumns(20);
        jtInfo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtInfo.setRows(5);
        jScrollPane1.setViewportView(jtInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbLimpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbVoltar.setForeground(new java.awt.Color(0, 0, 153));
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar-sada.png"))); // NOI18N
        jbVoltar.setText("VOLTAR");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVoltar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        Principal gui = new Principal();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jrGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrGeralActionPerformed
        definiTabela = 1;
        System.out.println("1");
    }//GEN-LAST:event_jrGeralActionPerformed

    private void jrMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMovimentoActionPerformed
        definiTabela = 2;
        System.out.println("2");
    }//GEN-LAST:event_jrMovimentoActionPerformed

    private void jrCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCursoActionPerformed
        definiTabela = 3;
        System.out.println("3");
    }//GEN-LAST:event_jrCursoActionPerformed

    private void jrDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDisciplinaActionPerformed
        definiTabela = 4;
        System.out.println("4");
    }//GEN-LAST:event_jrDisciplinaActionPerformed

    private void jrAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAlunoActionPerformed
        definiTabela = 5;
        System.out.println("5");
    }//GEN-LAST:event_jrAlunoActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Atenção!\nOs dados serão apagados\nTem certeza disso?","AVISO",JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_NO_OPTION){
            apagarBanco();
        }
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LimpezaBancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LimpezaBancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LimpezaBancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LimpezaBancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LimpezaBancoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JRadioButton jrAluno;
    private javax.swing.JRadioButton jrCurso;
    private javax.swing.JRadioButton jrDisciplina;
    private javax.swing.JRadioButton jrGeral;
    private javax.swing.JRadioButton jrMovimento;
    private javax.swing.JTextArea jtInfo;
    // End of variables declaration//GEN-END:variables
    
    private void apagarBanco(){
        MovimentoDAO dao = new MovimentoDAO();
        
        switch (definiTabela){
            case 1 :
                dao.excluirGeral();
                jtInfo.setText("Todos os dados foram apagados!");
                break;
            case 2 :
                dao.excluirMov();
                jtInfo.setText("Todos os dados dos movimentos foram \napagados!");
                break;
            case 3 :
                dao.excluirMov();
                dao.excluirCurDisc();
                dao.excluirDisciplina();
                dao.excluirCurso();
                jtInfo.setText("Todos os dados dos cursos foram \napagados!");
                break;
            case 4 :
                dao.excluirMov();
                dao.excluirCurDisc();
                dao.excluirDisciplina();
                jtInfo.setText("Todos os dados das disciplinas foram \napagados!");
                break;
            case 5 :
                dao.excluirMov();
                dao.excluirTelefone();
                dao.excluirAluno();
                jtInfo.setText("Todos os dados dos alunos foram \napagados!");
                break;
            default :
                JOptionPane.showMessageDialog(null, "Erro ao apagar banco!");
        }
    }
}
