/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Auxiliar.Erros;
import Auxiliar.ValidaCampos;
import DAO.MovimentoDAO;
import Objetos.Movimento;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author asfmegas
 */
public class MovimentoGUI extends javax.swing.JFrame {
    private DefaultTableModel tmMovimento = new DefaultTableModel(null,new String[]{"NOME","TURMA","N1(NP1)","N2(NP1)","N3(NP1)","N1(NP2)","N2(NP2)","N3(NP2)","FALTAS","DATA"});
    private int idmov;
    private List<Movimento> listaMov;
    private ListSelectionModel lsmMovimento;
    private SimpleDateFormat data = new SimpleDateFormat("yyyy-MM-dd");
    private Date hoje = new Date();
    /**
     * Creates new form MovimentoGUI
     */
    private final ButtonGroup bg;
    
    public MovimentoGUI() {
        setTitle("MOVIMENTO - SADA V 1.1");
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        //Desabilitar campos
        jtNome.setEditable(false);
        jtCurso.setEditable(false);
        jtDisc.setEditable(false);
        jtNP1.setEditable(false);
        jtNP2.setEditable(false);
        jtMedia.setEditable(false);
        jtRFaltas.setEditable(false);
        jtTurma.setEditable(false);
        jtData.setEditable(false);
        //foco no jtPesquisa
        jtPesquisa.requestFocus();
        
        //ButtonGrupo
        bg = new ButtonGroup();
        bg.add(jrDisc);
        bg.add(jrCurso);
        bg.add(jrAluno);
        bg.add(jrTurma);
        jrAluno.setSelected(true);
        
        /**
         * Modificar cabeçalho da jTable
         * Ashish Gupta 
            Ranch Hand 

            Joined: Apr 27, 2003
            Posts: 61
         * http://www.coderanch.com/t/336961/GUI/java/JTABLE-header-BOLD
         * acessado 05/10/2014
         */
        JTableHeader th = jtTabela.getTableHeader();
        th.setFont(new Font("Arial", Font.BOLD, 14));
        
        jtPesquisa.setDocument(new CustomDocument());
        jtTabela.getTableHeader().setReorderingAllowed(false); 
        int x = 0;
        //tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(150);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(100);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(30);
        
        jtFaltas.setText("0");
        
        infor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbAlterar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtCurso = new javax.swing.JTextField();
        jtDisc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtTurma = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtData = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtNota3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtNota1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtNota2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtNP1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtRFaltas = new javax.swing.JTextField();
        jtFaltas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtNota4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtNota5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtNota6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtNP2 = new javax.swing.JTextField();
        jtMedia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jrAluno = new javax.swing.JRadioButton();
        jrCurso = new javax.swing.JRadioButton();
        jrDisc = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jtPesquisa = new javax.swing.JTextField();
        jbConsulta = new javax.swing.JButton();
        jrTurma = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAlterar.setForeground(new java.awt.Color(0, 0, 204));
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar-sada.png"))); // NOI18N
        jbAlterar.setText("ALTERAR");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLimpar.setForeground(new java.awt.Color(0, 0, 204));
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar-sada.png"))); // NOI18N
        jbLimpar.setText("LIMPAR");
        jbLimpar.setEnabled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExcluir.setForeground(new java.awt.Color(0, 0, 204));
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir-sada.png"))); // NOI18N
        jbExcluir.setText("EXCLUIR");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbFechar.setForeground(new java.awt.Color(0, 0, 204));
        jbFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar-sada.png"))); // NOI18N
        jbFechar.setText("VOLTAR");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNovo.setForeground(new java.awt.Color(0, 0, 204));
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo-sada.png"))); // NOI18N
        jbNovo.setText("NOVO");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFechar)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbExcluir, jbLimpar, jbNovo});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbFechar))
                    .addComponent(jbNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Curso:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Disciplina:");

        jtNome.setBackground(new java.awt.Color(51, 204, 255));
        jtNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtCurso.setBackground(new java.awt.Color(51, 204, 255));
        jtCurso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtDisc.setBackground(new java.awt.Color(51, 204, 255));
        jtDisc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Turma:");

        jtTurma.setBackground(new java.awt.Color(51, 204, 255));
        jtTurma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Última Alterção:");

        jtData.setBackground(new java.awt.Color(51, 204, 255));
        jtData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDisc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NOTA 1");

        jtNota3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota3.setEnabled(false);
        jtNota3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota3FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOTA 2");

        jtNota1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota1.setEnabled(false);
        jtNota1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota1FocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NOTA 3");

        jtNota2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota2.setEnabled(false);
        jtNota2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota2FocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("NP1");

        jtNP1.setBackground(new java.awt.Color(51, 204, 255));
        jtNP1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("+");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("+");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("/3 =");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FALTA(S)");

        jtRFaltas.setBackground(new java.awt.Color(51, 204, 255));
        jtRFaltas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtRFaltas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtFaltas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtFaltas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFaltas.setEnabled(false);
        jtFaltas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtFaltasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFaltasFocusLost(evt);
            }
        });
        jtFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFaltasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("NOTA 1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("NOTA 2");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("NOTA 3");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("NP2");

        jtNota4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota4.setEnabled(false);
        jtNota4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota4FocusLost(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("+");

        jtNota5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota5.setEnabled(false);
        jtNota5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota5FocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("+");

        jtNota6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota6.setEnabled(false);
        jtNota6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota6FocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("/3 =");

        jtNP2.setBackground(new java.awt.Color(51, 204, 255));
        jtNP2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtMedia.setBackground(new java.awt.Color(51, 204, 255));
        jtMedia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("MÉDIA");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("(NP1 + NP2) / 2 = ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNota6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addComponent(jLabel15))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNP2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNP1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtRFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(148, 148, 148))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtNota1, jtNota2, jtNota3, jtRFaltas});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtNota4, jtNota5, jtNota6});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jtNP1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtRFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNota6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jtNP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtNP1, jtNota1, jtNota2, jtNota3});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtNota4, jtNota5, jtNota6});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jrAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAluno.setText("Aluno");
        jrAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAlunoActionPerformed(evt);
            }
        });

        jrCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrCurso.setText("Curso");
        jrCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCursoActionPerformed(evt);
            }
        });

        jrDisc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrDisc.setText("Disciplina");
        jrDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDiscActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("NOME:");

        jtPesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisaActionPerformed(evt);
            }
        });

        jbConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-sada.png"))); // NOI18N
        jbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaActionPerformed(evt);
            }
        });

        jrTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrTurma.setText("Turma");
        jrTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jrAluno)
                        .addGap(16, 16, 16)
                        .addComponent(jrCurso)
                        .addGap(18, 18, 18)
                        .addComponent(jrDisc)
                        .addGap(9, 9, 9)
                        .addComponent(jrTurma)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPesquisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbConsulta)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrAluno)
                            .addComponent(jrCurso)
                            .addComponent(jrDisc)
                            .addComponent(jrTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtTabela.setModel(tmMovimento);
        jtTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmMovimento = jtTabela.getSelectionModel();
        lsmMovimento.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    selecionarLinhaTabela(jtTabela);
                }
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if(confirmarDados()){
            int resp = JOptionPane.showConfirmDialog(this, "Deseja excluir o movimento?\n","Confirmação",JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_NO_OPTION){
                excluirMov();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um movimento para a exclusão!");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        Principal gui = new Principal();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jtFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFaltasActionPerformed
        
    }//GEN-LAST:event_jtFaltasActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        CadastroMovGUI gui = new CadastroMovGUI();
        limparCampos();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaActionPerformed
        try {
            listarMov();
        } catch (SQLException ex) {
            Logger.getLogger(MovimentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultaActionPerformed

    private void jrAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAlunoActionPerformed
        getCampo();
    }//GEN-LAST:event_jrAlunoActionPerformed

    private void jrCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCursoActionPerformed
        getCampo();
    }//GEN-LAST:event_jrCursoActionPerformed

    private void jrDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDiscActionPerformed
        getCampo();
    }//GEN-LAST:event_jrDiscActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumeros(1, 4, jtFaltas.getText()) == 3)
            if(confirmarDados()){
                alterarMov();
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um movimento.");
            }

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtNota2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota2FocusGained
        jtNota2.selectAll();
    }//GEN-LAST:event_jtNota2FocusGained

    private void jtNota3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota3FocusGained
        jtNota3.selectAll();
    }//GEN-LAST:event_jtNota3FocusGained

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        if(confirmarDados()){
            limparCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um movimento.");
        }
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNota3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota3FocusLost
        validarNota3();
        jtNota4.requestFocus();
    }//GEN-LAST:event_jtNota3FocusLost

    private void jtFaltasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFaltasFocusLost
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumeros(1,4,jtFaltas.getText()) != 3){
            JOptionPane.showMessageDialog(null, "Este valor não é válido!\nApenas números inteiros até 4 dígitos");
            jtFaltas.requestFocus();
        }else {
            jbAlterar.requestFocus();
        }     
    }//GEN-LAST:event_jtFaltasFocusLost

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if(confirmarDados()){
            alterarMov();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um movimento.");
        }
    }//GEN-LAST:event_jbAlterarKeyPressed

    private void jtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisaActionPerformed
        try {
            listarMov();
        } catch (SQLException ex) {
            Logger.getLogger(MovimentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtPesquisaActionPerformed

    private void jtNota2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota2FocusLost
        validarNota2();
    }//GEN-LAST:event_jtNota2FocusLost

    private void jtFaltasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFaltasFocusGained
        jtFaltas.selectAll();
    }//GEN-LAST:event_jtFaltasFocusGained

    private void jtNota4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota4FocusGained
        jtNota4.selectAll();
    }//GEN-LAST:event_jtNota4FocusGained

    private void jtNota4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota4FocusLost
        validarNota4();
    }//GEN-LAST:event_jtNota4FocusLost

    private void jtNota5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota5FocusGained
        jtNota5.selectAll();
    }//GEN-LAST:event_jtNota5FocusGained

    private void jtNota5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota5FocusLost
        validarNota5();
    }//GEN-LAST:event_jtNota5FocusLost

    private void jtNota6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota6FocusGained
        jtNota6.selectAll();
    }//GEN-LAST:event_jtNota6FocusGained

    private void jtNota6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota6FocusLost
        validarNota6();
    }//GEN-LAST:event_jtNota6FocusLost

    private void jrTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTurmaActionPerformed
        getCampo();
    }//GEN-LAST:event_jrTurmaActionPerformed

    private void jtNota1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota1FocusLost
        validarNota1();
    }//GEN-LAST:event_jtNota1FocusLost

    private void jtNota1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota1FocusGained
        jtNota1.selectAll();
    }//GEN-LAST:event_jtNota1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsulta;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JRadioButton jrAluno;
    private javax.swing.JRadioButton jrCurso;
    private javax.swing.JRadioButton jrDisc;
    private javax.swing.JRadioButton jrTurma;
    private javax.swing.JTextField jtCurso;
    private javax.swing.JTextField jtData;
    private javax.swing.JTextField jtDisc;
    private javax.swing.JTextField jtFaltas;
    private javax.swing.JTextField jtMedia;
    private javax.swing.JTextField jtNP1;
    private javax.swing.JTextField jtNP2;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNota1;
    private javax.swing.JTextField jtNota2;
    private javax.swing.JTextField jtNota3;
    private javax.swing.JTextField jtNota4;
    private javax.swing.JTextField jtNota5;
    private javax.swing.JTextField jtNota6;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtRFaltas;
    private javax.swing.JTable jtTabela;
    private javax.swing.JTextField jtTurma;
    // End of variables declaration//GEN-END:variables
   
    //Classe para manter caixa alta no JTextField
    //Referência
    //http://www.guj.com.br/java/199701-jtextfield-com-caixa-altaresolvido
    public class CustomDocument extends PlainDocument {

        @Override
	public void insertString(int offset, String str, AttributeSet attr)
			throws BadLocationException {
		if (str == null)
			return;
		super.insertString(offset, str.toUpperCase(), attr); // Detalhe no str
	}
    }
    
    public void ativarCampos(){
        jtNota1.setEnabled(true);
        jtNota2.setEnabled(true);
        jtNota3.setEnabled(true);
        jtNota4.setEnabled(true);
        jtNota5.setEnabled(true);
        jtNota6.setEnabled(true);
        jtFaltas.setEnabled(true);
        jbAlterar.setEnabled(true);
        jbLimpar.setEnabled(true);
        jbExcluir.setEnabled(true);
    }
    
    private void limparCampos(){
        jtNome.setText("");
        jtCurso.setText("");
        jtDisc.setText("");
        jtNota1.setText("");
        jtNota2.setText("");
        jtNota3.setText("");
        jtNota4.setText("");
        jtNota5.setText("");
        jtNota6.setText("");
        jtRFaltas.setText("");
        jtFaltas.setText("0");
        jtTurma.setText("");
        jtData.setText("");
        jtNP2.setText("");
        jtNP1.setText("");
        jtMedia.setText("");
    }
    
    private void listarMov() throws SQLException{
        MovimentoDAO dao = new MovimentoDAO();
        listaMov = dao.pesquisar(getCampo(),"%"+jtPesquisa.getText()+"%");
        moastrarPesquisa(listaMov);
    }
//"ID","NOME","NASCIMENTO","CURSO","DISCIPLINA","NOTA 1","NOTA 2","NOTA 3","FALTAS"
    private void moastrarPesquisa(List<Movimento> mov) {
        while(tmMovimento.getRowCount() > 0){
            tmMovimento.removeRow(0);
        }
        if(mov.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sua lista está vazia!");
        }else{
            String[] linhas = new String[]{null,null,null,null,null,null,null,null,null};
            for(int i=0; i < mov.size();i++){
                tmMovimento.addRow(linhas);
                tmMovimento.setValueAt(mov.get(i).getNome(), i, 0);
                tmMovimento.setValueAt(mov.get(i).getTurma(), i, 1);
                tmMovimento.setValueAt(mov.get(i).getNota1(), i, 2);
                tmMovimento.setValueAt(mov.get(i).getNota2(), i, 3);
                tmMovimento.setValueAt(mov.get(i).getNota3(), i, 4);
                tmMovimento.setValueAt(mov.get(i).getNota3(), i, 5);
                tmMovimento.setValueAt(mov.get(i).getNota3(), i, 6);
                tmMovimento.setValueAt(mov.get(i).getNota3(), i, 7);
                tmMovimento.setValueAt(mov.get(i).getFaltas(), i, 8);
                tmMovimento.setValueAt(formatarDataCampo(mov.get(i).getDataAlteracao()), i, 9);
            }
        }
    }
    
    private void selecionarLinhaTabela(JTable tabela){
        if(jtTabela.getSelectedRow() != -1){
            ativarCampos();
            jtNome.setText(listaMov.get(tabela.getSelectedRow()).getNome());
            jtCurso.setText(listaMov.get(tabela.getSelectedRow()).getNomeCurso());
            jtDisc.setText(listaMov.get(tabela.getSelectedRow()).getNomeDisc());
            jtNota1.setText(""+listaMov.get(tabela.getSelectedRow()).getNota1());
            jtNota2.setText(""+listaMov.get(tabela.getSelectedRow()).getNota2());
            jtNota3.setText(""+listaMov.get(tabela.getSelectedRow()).getNota3());
            jtNota4.setText(""+listaMov.get(tabela.getSelectedRow()).getNota4());
            jtNota5.setText(""+listaMov.get(tabela.getSelectedRow()).getNota5());
            jtNota6.setText(""+listaMov.get(tabela.getSelectedRow()).getNota6());
            jtRFaltas.setText(""+listaMov.get(tabela.getSelectedRow()).getFaltas());
            jtTurma.setText(listaMov.get(tabela.getSelectedRow()).getTurma());
            jtData.setText(formatarDataCampo(listaMov.get(tabela.getSelectedRow()).getDataAlteracao()));
            idmov = listaMov.get(tabela.getSelectedRow()).getIdMov();
            jtNP1.setText(""+calcularNP1());
            jtNP2.setText(""+calcularNP2());
            jtMedia.setText(""+calcularMedia());
            jtFaltas.setText("0");
        }else{
            jtNome.setText("");
            jtCurso.setText("");
            jtDisc.setText("");
            jtNota1.setText("");
            jtNota2.setText("");
            jtNota3.setText("");
            jtNota4.setText("");
            jtNota5.setText("");
            jtNota6.setText("");
            jtRFaltas.setText("");
            jtFaltas.setText("0");
            jtTurma.setText("");
            jtData.setText("");
            jtNP2.setText("");
            jtNP1.setText("");
            jtMedia.setText("");
        }
    }
    
    private String getCampo(){
        String campo = "";
        if(jrAluno.isSelected()){
            campo = "a.nome";
        }else if(jrCurso.isSelected()){
            campo = "c.especificacao";
        }else if(jrDisc.isSelected()){
            campo = "d.especificacao";
        }else if (jrTurma.isSelected()){
            campo = "m.turma";
        }
        return campo;
    }
    /**
     * Formatacao de double para duas casas decimais retirada do forum
     * http://www.guj.com.br/java/296574-restringir-double-para-apenas-duas-casas-decimais
     * acessado em 24-09-2014
     * @return 
     */
    private double calcularNP1(){
        
        try{
            double nota1 = Double.parseDouble(jtNota1.getText());
            double nota2 = Double.parseDouble(jtNota2.getText());
            double nota3 = Double.parseDouble(jtNota3.getText());
            double media = (nota1+nota2+nota3)/3;
            return Double.valueOf(String.format(Locale.US, "%.2f", media));
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro fatal.\n"+e.getMessage());
            return 0;
        }
        
    }
    
    private double calcularNP2(){
        try {
            double nota1 = Double.parseDouble(jtNota4.getText());
            double nota2 = Double.parseDouble(jtNota5.getText());
            double nota3 = Double.parseDouble(jtNota6.getText());
            double media = (nota1+nota2+nota3)/3;
            return Double.valueOf(String.format(Locale.US, "%.2f", media));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro fatal.\n"+e.getMessage());
            return 0;
        }
    }
    
    private double calcularMedia(){
        try {
            double nota1 = Double.parseDouble(jtNP1.getText());
        double nota2 = Double.parseDouble(jtNP2.getText());
        double media = (nota1+nota2)/2;
        return Double.valueOf(String.format(Locale.US, "%.2f", media));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro fatal.\n"+e.getMessage());
            return 0;
        }   
    }
            
    private int calcularFaltas(){
        int faltasCadastradas = 0;
        int faltasAcrescentadas = 0;
        if(!jtFaltas.equals("")){
            faltasCadastradas = Integer.parseInt(jtFaltas.getText());
            faltasAcrescentadas = Integer.parseInt(jtRFaltas.getText());
        }
        return faltasCadastradas + faltasAcrescentadas;
    }
    
    private void alterarMov(){
        Movimento mov = new Movimento();
        MovimentoDAO dao = new MovimentoDAO();
        mov.setIdMov(idmov);
        mov.setNota1(Double.parseDouble(jtNota1.getText()));
        mov.setNota2(Double.parseDouble(jtNota2.getText()));
        mov.setNota3(Double.parseDouble(jtNota3.getText()));
        mov.setNota4(Double.parseDouble(jtNota4.getText()));
        mov.setNota5(Double.parseDouble(jtNota5.getText()));
        mov.setNota6(Double.parseDouble(jtNota6.getText()));
        mov.setFaltas(calcularFaltas());
        mov.setTurma(jtTurma.getText());
        mov.setDataAlteracao(data.format(hoje));
        dao.alterar(mov);
        jtFaltas.setText("0");
        limparCampos();
        try {
            listarMov();
        } catch (SQLException ex) {
            Erros.erroSql("Erro ao tentar alterar dados!\n"+ex.getMessage());
        }
        jtNP1.setText("");
    }
    
    private void excluirMov(){
        MovimentoDAO dao = new MovimentoDAO();
        dao.excluir(idmov);
        jtFaltas.setText("0");
        limparCampos();
        try {
            listarMov();
        } catch (SQLException ex) {
            Erros.erroSql("Erro ao tentar excluir dados!\n"+ex.getMessage());
        }
        jtNP1.setText("");
    }
    
    private String formatarDataCampo(String data){
        char[] num = new char[data.length()];
        for(int i=0; i < data.length(); i++){
            num[i] = data.charAt(i);
        }
        String dia = ""+num[8]+num[9];
        String mes = ""+num[5]+num[6];
        String ano = ""+num[0]+num[1]+num[2]+num[3];
        String d = dia+"/"+mes+"/"+ano;
            //1983-02-18
            //0 1 2 3 - 5 6 - 8 9
        return d;
    }
    
    private void validarNota1(){
        ValidaCampos vc = new ValidaCampos();
       
        int v = vc.validarNumeros(0, 5, jtNota1.getText());
        if(jtNota1.getText().equals(""))
            jtNota1.setText("0");
        
        if(v == 2){
                JOptionPane.showMessageDialog(null, "Não é um número válido!");
                jtNota1.requestFocus();
            }else{
                if(v == 7){
                    String novoTexto = jtNota1.getText().replace(',','.');
                    jtNota1.setText(novoTexto);
                    jtNP1.setText(""+calcularNP1());
                    jtMedia.setText(""+calcularMedia());
                }else if(v == 8){
                    jtNP1.setText(""+calcularNP1());
                    jtMedia.setText(""+calcularMedia());
                }else{
                    JOptionPane.showMessageDialog(null, "Este valor não é válido!");
                    jtNota1.requestFocus();
                }
            }   
    }
    
    private void validarNota2(){
        ValidaCampos vc = new ValidaCampos();
        int v = vc.validarNumeros(0, 5, jtNota2.getText());
        
        if(jtNota2.getText().equals(""))
            jtNota2.setText("0");
        
        if(v == 7){
            String novoTexto = jtNota2.getText().replace(',','.');
            jtNota2.setText(novoTexto);
            jtNP1.setText(""+calcularNP1());
            jtMedia.setText(""+calcularMedia());
        }else if(v == 8){
            jtNP1.setText(""+calcularNP1());
            jtMedia.setText(""+calcularMedia());
        }else{
            JOptionPane.showMessageDialog(null, "Este valor não é válido!");
            jtNota2.requestFocus();
        }
    }
    
    private void validarNota3(){
        if(jtNota3.getText().equals(""))
            jtNota3.setText("0");
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumeros(0, 5, jtNota3.getText()) == 7){
            String novoTexto = jtNota3.getText().replace(',','.');
            jtNota3.setText(novoTexto);
            jtNP1.setText(""+calcularNP1());
            jtMedia.setText(""+calcularMedia());
        }else if(vc.validarNumeros(0, 5, jtNota3.getText()) == 8){
            jtNP1.setText(""+calcularNP1());
            jtMedia.setText(""+calcularMedia());
        }else{
            JOptionPane.showMessageDialog(null, "Este valor não é válido!");
            jtNota3.requestFocus();
        }
    }
    
    private void infor(){
        jbAlterar.setToolTipText("Alterar dados.");
        jbExcluir.setToolTipText("Excluir dados.");
        jbNovo.setToolTipText("Novo cadastro.");
        jbLimpar.setToolTipText("Limpar campos.");
    }
    
    private void validarNota4(){
        if(jtNota4.getText().equals(""))
            jtNota4.setText("0");
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumeros(0, 5, jtNota4.getText()) == 7){
            String novoTexto = jtNota4.getText().replace(',','.');
            jtNota4.setText(novoTexto);
            jtNP2.setText(""+calcularNP2());
            jtMedia.setText(""+calcularMedia());
        }else if(vc.validarNumeros(0, 5, jtNota4.getText()) == 8){
            jtNP2.setText(""+calcularNP2());
            jtMedia.setText(""+calcularMedia());
        }else{
            JOptionPane.showMessageDialog(null, "Este valor não é válido!");
            jtNota4.requestFocus();
        }
    }
    
    private void validarNota5(){
        if(jtNota5.getText().equals(""))
            jtNota5.setText("0");
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumeros(0, 5, jtNota5.getText()) == 7){
            String novoTexto = jtNota5.getText().replace(',','.');
            jtNota5.setText(novoTexto);
        }else if(vc.validarNumeros(0, 5, jtNota5.getText()) == 8){
            jtNP2.setText(""+calcularNP2());
            jtMedia.setText(""+calcularMedia());
        }else{
            JOptionPane.showMessageDialog(null, "Este valor não é válido!");
            jtNota5.requestFocus();
        }
    }
    
    private void validarNota6(){
        if(jtNota6.getText().equals(""))
            jtNota6.setText("0");
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumeros(0, 5, jtNota6.getText()) == 7){
            String novoTexto = jtNota6.getText().replace(',','.');
            jtNota6.setText(novoTexto);
            jtNP2.setText(""+calcularNP2());
            jtMedia.setText(""+calcularMedia());
        }else if(vc.validarNumeros(0, 5, jtNota6.getText()) == 8){
            jtNP2.setText(""+calcularNP2());
            jtMedia.setText(""+calcularMedia());
        }else{
            JOptionPane.showMessageDialog(null, "Este valor não é válido!");
            jtNota6.requestFocus();
        }
    }
    
    private boolean confirmarDados(){
        if(!jtDisc.getText().equals("") && !jtNome.getText().equals("") && !jtCurso.getText().equals("")){
            return true;
        }else{
            return false;
        }
    }
    /*
    private boolean verificarCampos(){
        if(!jtNota1.getText().equals("") && !jtNota2.getText().equals("") && !jtNota3.getText().equals("") && !jtNota4.getText().equals("") && !jtNota5.getText().equals("") && !jtNota6.getText().equals(""))
            return true;
        else
            return false;
    }
    */
}
