/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAO.Conexao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author asfmegas
 */
public class Principal extends javax.swing.JFrame {
    private static int modelo;
    /**
     * Creates new form Principal
     */
    public Principal() {      
        initComponents();
        setTitle("SADA V 1.1 - Sistema de Análise de Desempenho Acadêmico");
        //setSize(700,500);
        setLocationRelativeTo(null);
        setResizable(false);
        infor();
        ativarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbMovimento = new javax.swing.JButton();
        jbEstudante = new javax.swing.JButton();
        jbDisciplina = new javax.swing.JButton();
        jbCurso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmEstudante = new javax.swing.JMenuItem();
        jmCurso = new javax.swing.JMenuItem();
        jmDiscimplina = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmMovimento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmSair = new javax.swing.JMenuItem();
        jmbConfig = new javax.swing.JMenu();
        jmConfig = new javax.swing.JMenuItem();
        jmLimpeza = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jbMovimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbMovimento.setForeground(new java.awt.Color(0, 0, 153));
        jbMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Movimento copy.png"))); // NOI18N
        jbMovimento.setText("MOVIMENTO");
        jbMovimento.setToolTipText("");
        jbMovimento.setEnabled(false);
        jbMovimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMovimentoActionPerformed(evt);
            }
        });
        jbMovimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbMovimentoKeyPressed(evt);
            }
        });
        jPanel1.add(jbMovimento);
        jbMovimento.setBounds(300, 130, 160, 195);

        jbEstudante.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbEstudante.setForeground(new java.awt.Color(0, 0, 153));
        jbEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ALUNO copy.png"))); // NOI18N
        jbEstudante.setText("ALUNO");
        jbEstudante.setToolTipText("");
        jbEstudante.setEnabled(false);
        jbEstudante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstudanteActionPerformed(evt);
            }
        });
        jbEstudante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbEstudanteKeyPressed(evt);
            }
        });
        jPanel1.add(jbEstudante);
        jbEstudante.setBounds(40, 30, 250, 93);

        jbDisciplina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbDisciplina.setForeground(new java.awt.Color(0, 0, 153));
        jbDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DISCIPLINA copy.png"))); // NOI18N
        jbDisciplina.setText("DISCIPLINA");
        jbDisciplina.setEnabled(false);
        jbDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDisciplinaActionPerformed(evt);
            }
        });
        jbDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbDisciplinaKeyPressed(evt);
            }
        });
        jPanel1.add(jbDisciplina);
        jbDisciplina.setBounds(40, 230, 250, 93);

        jbCurso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCurso.setForeground(new java.awt.Color(0, 0, 153));
        jbCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CURSO copy.png"))); // NOI18N
        jbCurso.setText("CURSO");
        jbCurso.setEnabled(false);
        jbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCursoActionPerformed(evt);
            }
        });
        jbCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCursoKeyPressed(evt);
            }
        });
        jPanel1.add(jbCurso);
        jbCurso.setBounds(40, 130, 250, 93);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SADAV11.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 30, 160, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundSada_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 350);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 350));

        jMenu1.setText("CADASTRO");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmEstudante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmEstudante.setText("ALUNO");
        jmEstudante.setEnabled(false);
        jmEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstudanteActionPerformed(evt);
            }
        });
        jMenu1.add(jmEstudante);

        jmCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmCurso.setText("CURSO");
        jmCurso.setEnabled(false);
        jmCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCursoActionPerformed(evt);
            }
        });
        jMenu1.add(jmCurso);

        jmDiscimplina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmDiscimplina.setText("DISCIPLINA");
        jmDiscimplina.setEnabled(false);
        jmDiscimplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDiscimplinaActionPerformed(evt);
            }
        });
        jMenu1.add(jmDiscimplina);
        jMenu1.add(jSeparator2);

        jmMovimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmMovimento.setText("MOVIMENTO");
        jmMovimento.setEnabled(false);
        jmMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMovimentoActionPerformed(evt);
            }
        });
        jMenu1.add(jmMovimento);
        jMenu1.add(jSeparator1);

        jmSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmSair.setText("SAIR");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmSair);

        jMenuBar1.add(jMenu1);

        jmbConfig.setText("CONFIGURAÇÃO");
        jmbConfig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmConfig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmConfig.setText("CONFIGURAÇÃO INICIAL");
        jmConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConfigActionPerformed(evt);
            }
        });
        jmbConfig.add(jmConfig);

        jmLimpeza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmLimpeza.setText("LIMPEZA DE BANCO");
        jmLimpeza.setEnabled(false);
        jmLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLimpezaActionPerformed(evt);
            }
        });
        jmbConfig.add(jmLimpeza);

        jMenuBar1.add(jmbConfig);

        jmSobre.setText("SOBRE");
        jmSobre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("Sobre o SADA");
        jmSobre.add(jMenuItem5);

        jMenuBar1.add(jmSobre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstudanteActionPerformed
        AlunoGUI gui = new AlunoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbEstudanteActionPerformed

    private void jbDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDisciplinaActionPerformed
        DisciplinaGUI gui = new DisciplinaGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbDisciplinaActionPerformed

    private void jbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCursoActionPerformed
        CursoGUI gui = new CursoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbCursoActionPerformed

    private void jmMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMovimentoActionPerformed
        CadastroMovGUI gui = new CadastroMovGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmMovimentoActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmDiscimplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDiscimplinaActionPerformed
        DisciplinaGUI gui = new DisciplinaGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmDiscimplinaActionPerformed

    private void jmCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCursoActionPerformed
        CursoGUI gui = new CursoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmCursoActionPerformed

    private void jmEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstudanteActionPerformed
        AlunoGUI gui = new AlunoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmEstudanteActionPerformed

    private void jbMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMovimentoActionPerformed
        MovimentoGUI gui = new MovimentoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbMovimentoActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        JOptionPane.showMessageDialog(null, "Ola!\nEste é o SADA Versão 1.1\nSistema de Análise de Desempenho Acadêmico\n"
                + "Sugestões entre em contato:\nasfsteel2012@gmail.com\nAssunto: 'Sugestão SADA'.");
    }//GEN-LAST:event_jLabel2MousePressed

    private void jmConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConfigActionPerformed
        ConfiguracaoGUI gui = new ConfiguracaoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmConfigActionPerformed

    private void jbEstudanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbEstudanteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            AlunoGUI gui = new AlunoGUI();
            gui.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbEstudanteKeyPressed

    private void jbCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCursoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CursoGUI gui = new CursoGUI();
            gui.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbCursoKeyPressed

    private void jbDisciplinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbDisciplinaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DisciplinaGUI gui = new DisciplinaGUI();
            gui.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbDisciplinaKeyPressed

    private void jbMovimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbMovimentoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            MovimentoGUI gui = new MovimentoGUI();
            gui.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbMovimentoKeyPressed

    private void jmLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLimpezaActionPerformed
        LimpezaBancoGUI gui = new LimpezaBancoGUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmLimpezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jbCurso;
    private javax.swing.JButton jbDisciplina;
    private javax.swing.JButton jbEstudante;
    private javax.swing.JButton jbMovimento;
    private javax.swing.JMenuItem jmConfig;
    private javax.swing.JMenuItem jmCurso;
    private javax.swing.JMenuItem jmDiscimplina;
    private javax.swing.JMenuItem jmEstudante;
    private javax.swing.JMenuItem jmLimpeza;
    private javax.swing.JMenuItem jmMovimento;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenu jmbConfig;
    // End of variables declaration//GEN-END:variables

    private void infor(){
        jbCurso.setToolTipText("Cadastro, alteração e exclusão de Curso.");
        jbDisciplina.setToolTipText("Cadastro, alterarção e exclusão de Disciplina.");
        jbEstudante.setToolTipText("Cadastro, alteração e exclusão de Aluno.");
        jbMovimento.setToolTipText("Movimentação de Aluno.");
    }
    
    private void ativarBotoes(){
        if(Conexao.ativar == true){
            jbCurso.setEnabled(true);
            jbDisciplina.setEnabled(true);
            jbEstudante.setEnabled(true);
            jbMovimento.setEnabled(true);
            jmCurso.setEnabled(true);
            jmDiscimplina.setEnabled(true);
            jmEstudante.setEnabled(true);
            jmMovimento.setEnabled(true);
            jmLimpeza.setEnabled(true);
        }
    }
}
